### ISSUE TITLE
Documentation for new screen modes added in VDP 1.03RC2

### ISSUE THREAD

**Issue by julianregel** [breakintoprogram/agon-vdp#103]
There doesn't appear to be a way to add pages to the Agon Wiki, so raising this as an issue here.

Please see attached a new page detailing the screen modes for the Agon Light VDP1.03RC2.

Thanks

[Agon-Screen-Modes.md](https://github.com/breakintoprogram/agon-vdp/files/12774671/Agon-Screen-Modes.md)

**Comment by breakintoprogram** [comment]
Hi @julianregel this has now been added to the documentation.

https://github.com/breakintoprogram/agon-docs/wiki/VDP#screen-modes
