### ISSUE TITLE
VDU to get a keycode

### ISSUE THREAD

**Issue by DjPoke** [breakintoprogram/agon-vdp#108]
Hi,
Can you give me an ez80 asm example to get a keycode from the VDU ?
Actually, i'm doing this, but i'm wrong :

```
ld a,23
rst.lis $10
ld a,0
rst.lis $10
ld a,$01
rst.lis $10

ld a,(ix+0) ; ???
ld a,(ix+1) ; ???
ld a,(ix+2) ; ???
ld a,(ix+3) ; ???
```

**Comment by lennart-benschop** [comment]
Normally you don't send a VDU code to read a key. You have the RST 8 system call with A=0, like LD A,0 RST.L 08h. That waits for a key.  If you do not want to wait, you can peek the sysvars. First do LD A,8 RST.L 08h to get the sysvars address into IX, then peek the sysvars (ix+5) for key code, (ix+24) for up/down status, (ix+6) for modifier keys (shift/control).

**Comment by DjPoke** [comment]
Thanks a lot :)
