### ISSUE TITLE
[Feature request] a VDU command to change only a byte in a bitmap, and some other stuffs

### ISSUE THREAD

**Issue by DjPoke** [breakintoprogram/agon-vdp#112]
Hi,
I think it can be usefull to quickly change only a byte/pixel color value in a bitmap.
An this can take effect in the sprites using that bitmap.
This vdu command should be used only after a bitmap is created.

Also, a vdu command to load bitmap data from memory, and a vdu/mos command to load bitmaps from disk, can be very usefull for games creation.

**Comment by stevesims** [comment]
FYI, this is supported via the buffered commands API
