### ISSUE TITLE
Help wanted - How to get audio status (audio command 1) ?

### ISSUE THREAD

**Issue by DjPoke** [breakintoprogram/agon-vdp#120]
Hi,
What register receive the audio status (audio command 1) ?

```
wait_chan0_active:
	CALL wait_VBL
	
	LD A,23
	LD A,0
	LD A,$85
	LD A,0 ; channel
	LD A,1 ; command
	
        LD A,???

	AND 1
	CP 1
	JR NZ,wait_chan0_active
	
	RET

```

**Comment by richardturnnidge** [comment]
Just been struggling with this myself... Assuming you are on 1.04RC2 for this feature to work... You need an rst.lil $10 after each LD A instructions that you have to send the bytes to VDP. The result does not come back to any register, it gets put into the sysvar_audioSuccess system variable. See: https://github.com/breakintoprogram/agon-docs/wiki/MOS-API#system-variables. It may not a moment, it is not an instant reply.

**Comment by DjPoke** [comment]
Thanks

**Comment by DjPoke** [comment]
I'm doing this but while a note is playing, the status flag never return 3 :

```
wait_chan0_stop:
	LD A,23
	RST.LIS $10
	LD A,0
	RST.LIS $10
	LD A,$85
	RST.LIS $10
	LD A,0 ; channel
	RST.LIS $10
	LD A,1 ; command
	RST.LIS $10

	MOSCALL mos_sysvars
	LD A,(IX+sysvar_audioSuccess)

	AND 3 ; active and playing ?
	CP 3
	JR Z,wait_chan0_stop ; loop

	RET
```

**Comment by richardturnnidge** [comment]
Have a look on the Agon programmers Discord server, Steve went through the basics with me, check the 'music, general' section. I wrote a dead simple Basic version first based on his sample to check the system was doing the correct thing, then applied to Assembly. I found my code needed to go off and do something else for a while after sending the status request and checking for the answer.
https://discord.com/channels/1080130527908069467

**Comment by DjPoke** [comment]
Right. A simple 'wait VBL', after checking for the status, seems to do the job.

```
; wait vblank
wait_VBL:
	MOSCALL mos_sysvars
	
	LD A,(IX+sysvar_time)
	LD B,A

wv_loop:
        MOSCALL mos_sysvars
	LD A,(IX+sysvar_time)
	CP B
	JR Z,wv_loop
	
	RET
```
