### ISSUE TITLE
Key up events rollover

### ISSUE THREAD

**Issue by jackokring** [breakintoprogram/agon-vdp#134]
In `agon_ps2.h`

```
	#endif
	
	if (kb->getNextVirtualKey(&item, 0)) {
		//if (item.down) {//keycode up events are still true mapping. how would _keycode change?
			switch (item.vk) {
				case fabgl::VK_LEFT:
					_keycode = 0x08;
```

**Comment by stevesims** [comment]
in the real code that `if` statement is not commented out, and so the `switch` statement that follows which will result in `_keycode` being updated will only run for key down events.

therefore for key up events, the value returned via the `keycode` argument will be whatever `_keycode` was last set to.

the keyboard data packet sent thru to MOS via the VDP protocol will include that returned `keycode`, as well as the `item.vk` and `item.down`
