### ISSUE TITLE
Feature request: Changing video modes should preserver colour scheme

### ISSUE THREAD

**Issue by avalonbits** [breakintoprogram/agon-vdp#144]
Today, whenever we change the video mode, the foreground and background colors will also change to white / black, respectively.

The FG/BG colours should be preserved across screen mode changes.

**Comment by stevesims** [comment]
the VDU system is written to be similar to Acorn's VDU system.  on an Acorn system when you changed screen mode, the colours get reset to their default values, i.e. black and white

preserving fg/bg colours would differ from this behaviour

you can clear the graphics area whilst preserving graphics FG and BG colours using VDU 16 (`CLG` in BASIC)

**Comment by avalonbits** [comment]
Ok, fair enough. I'll close this issue.
