### ISSUE TITLE
Set keyboard delay and rate, and get/set the LED state

### ISSUE THREAD

**Issue by james7780** [breakintoprogram/agon-vdp#19]
~~The fabgl::Keyboard class maintains virtual key state for every key on the keyboard.~~

~~It would be useful (for games, interactive apps and BBCBASIC INKEY scan for keypress) to be able to query the VDP for the current virtual key state (up / down / held) of any key. The VDP could then use fabgl::Keyboard.isVKDown() to return the key state.~~

~~As far as I understand the VDP currently only keeps track of the last pressed key (using Keyboard::getNextVirtualKey()).~~

It would also be nice to be able to send PS/2 commands to the keyboard via VDP, to eg switch the keyboard LEDs on or off, or set key repeat rate.

**Comment by breakintoprogram** [comment]
The keyboard read work has been done in MOS/VDP 1.03 already, and BBC BASIC's INKEY$ handling much improved.
I will look at sending PS/2 commands to the keyboard as requested.
