### ISSUE TITLE
VDP 1.03 RC1 Keyboard Issue

### ISSUE THREAD

**Issue by leventp** [breakintoprogram/agon-vdp#22]
Hi,
Just installed VDP 1.03 on my Agon Light 2 (Olimex) via Aurdino. All went fine but upon powering on Agon, each key were duplicated when a single was pressed. That is key stroke 'A' reflected as 'AA'
The only way I could install the new MOS 1.03 RC1 was to create an autoexec.txt file with the corresponding FLASH command in it. After that all was fine and able to run the BBC BASIC 1.04 Pre-release version. 
Keep up the good work. 
P.S. This may not be an issue if MOS 1.03 installed before VDP 1.03. Not sure what is the order.

**Comment by warrengc3** [comment]
@leventp I had an issue with MOS 1.3 RC1 and VDP 1.03 RC1 that is similar.  However mine is where I have to hit enter twice after a command. From there my sample programs do not appear to run correctly as I get a blank screen and no output.
I can post a video if needed.  I would try and move to 1.04 but I do not have the Zlog cable.
