### ISSUE TITLE
Add VDU commands for window operations

### ISSUE THREAD

**Issue by breakintoprogram** [breakintoprogram/agon-vdp#29]
`VDU 24,left;bottom;right;top;`: Set graphics viewport
`VDU 28,left,bottom,right,top`: Set text viewport
`VDU 26`: Reset graphics and text viewports

- All graphics and text operations to be relative to those viewports.
- CLS and CLG will clear the viewport, not the canvas, if a viewport is set.
  - They will use the faster Canvas->clear() if no viewports have been set, or after a VDU 26.
  - They will not use the faster Canvas->clear() if the text viewport is defined to be the full canvas size.

**Comment by lennart-benschop** [comment]
One thing: what should the mode parameters return when you call VDU 23, &86?
- the dimensions of the entire screen?
- the dimensions of the currently selected text and graphics windows
- the dimensions of the entire screen plus the full window parameters (origin + dimensions)? This would make the returned packet quite large.
Or should we have a separate VDU command to return the window parameters?

**Comment by lennart-benschop** [comment]
VDU31 should position the cursor relative to the text window, so VDU31,0,0 should place it at the top left corner of that window. Currently it is positioned relative to the top left corner of the whole screen.
