### ISSUE TITLE
Investigate slow text output

### ISSUE THREAD

**Issue by breakintoprogram** [breakintoprogram/agon-vdp#40]
Investigate an allegation by Igor Chaves Cananea on the Agon Facebook group that the text output is significantly slower in the later release candidates (after 1.03 RC1).

**Comment by breakintoprogram** [comment]
There was a wait_completion in the vdu function that was intended to wait for any graphical operations to complete. It was also waiting for text to be updated. This is probably over-zealous, so have modified the code to work as intended.

**Comment by breakintoprogram** [comment]
Okay this seems to work - possibly add one final refinement:

- At the start of VDU, set a global variable (doWaitComplete) to false
- Any operation that requires a wait sets that to true
- At the end only do a waitComplete if that flag is set to true

**Comment by nihirash** [comment]
Do we really need "doWaitCompletion = true" in bitmap blitting(draw bitmap) operation?

I didn't meet any issues with disabled this flag but got really big speed improvement or maybe my situation is kind of survivorship bias.
