### ISSUE TITLE
Implement the mode parameter of GCOL for drawing commands

### ISSUE THREAD

**Issue by breakintoprogram** [breakintoprogram/agon-vdp#49]
- 0: Plot the specified colour
- 1: OR the colour with the colour already there
- 2: AND the colour with the colour already there
- 3: XOR the colour with the colour already there
- 4: NOT (invert) the colour already there
- 5: No change to colour already there
- 6: Clear the colour - set it to colour 0

NB: FabGL only supports NOT and swapping the foreground and background colours

**Comment by breakintoprogram** [comment]
Think the only modes FabGL can support are: 0, 4, 6. All other modes will have no effect as per 5. 

Not sure how the swap fg/bg colour option works.

**Comment by lennart-benschop** [comment]
Swap fg/bg is supposed to work like this: for every point you visit:
- if it has the foreground colour, change it to background colour.
- else if it has the background colour, change it to foreground colour.
- else leave the point unchanged.

**Comment by lennart-benschop** [comment]
I would also implement the distinct 0..7 plot modes:
0..3 use relative coordinates.
4..7 use absolute coordinates
0,4 move, do not draw anything.
1,5 draw in foreground colour.
2,6 draw in inverse colour (this is FabGL's NOT operation I think).
3,7 draw in background colour
 FabGL appears to have inverse colour support only for dots and lines, but it would be good to implement all these modes for them. Relative coordinates, fg and bg drawing can also be implemented for the other graphics primitives.

**Comment by breakintoprogram** [comment]
That's not part of the scope for this card.

**Comment by lennart-benschop** [comment]
I'll make another card for it then.
