### ISSUE TITLE
Add terminal support for CP/M

### ISSUE THREAD

**Issue by breakintoprogram** [breakintoprogram/agon-vdp#5]
As an Agon user
I would like to switch to a CP/M compatible terminal mode
Without having to reload the VDP with different code

Acceptance Criteria:

- Need to be able to switch mode in MOS before starting CP/M
- It's a one-way trip, no way to exit CP/M terminal mode without resetting the Agon

**Comment by snakebyte69** [comment]
Do you have an ETA on this one?
