### ISSUE TITLE
VDU 30 is performing carriage return rather than cursor home

### ISSUE THREAD

**Issue by leighbb** [breakintoprogram/agon-vdp#62]
Expected behaviour:

VDU 30 should move the cursor to the top left (as per documentation)

Observed behaviour:

VDU 30 is moving the cursor to the left on the current line

**Comment by leighbb** [comment]
I have created a pull request to correct this issue, and the issue with VDU 28.

**Comment by breakintoprogram** [comment]
Closing this as 'Won't Do' as it duplicates the push request #64
