### ISSUE TITLE
VDU 28 is not performing as expected

### ISSUE THREAD

**Issue by leighbb** [breakintoprogram/agon-vdp#63]
Whilst porting MicroEMACS I have been using VDU 28 to simulate clear to end of line and clear to end of page.
During testing I noticed VDU 28 was not behaving as expected. I compared the behaviour to the Linux version
of BBC BASIC, and they are not behaving the same.

I have created a pull request to correct this issue.

**Comment by leighbb** [comment]
Pull request #64 submitted to fix this.

**Comment by breakintoprogram** [comment]
Closing this as 'Won't Do' as it duplicates the push request #64
