### ISSUE TITLE
Arduino IDE - fabGL and vdp-gl clash

### ISSUE THREAD

**Issue by snakebyte69** [breakintoprogram/agon-vdp#69]
Many Agonians have Agon Light(s) and other fabGL boards, can the naming be changed so VDP only references vdp-gl?

**Comment by breakintoprogram** [comment]
This is not a VDP issue, it's an issue with the vdp-gl library which I do not maintain. Suggest you contact the maintainer of that project, Igor Chaves Cananea, on [his project page](https://github.com/avalonbits/vdp-gl). Closing this card as 'Won't Do'
