### ISSUE TITLE
VDU 24 behaves differently from original BBC BASIC

### ISSUE THREAD

**Issue by leventp** [breakintoprogram/agon-vdp#71]
Looks like when setting a graphic  window using VDU 24, the origin is automatically set to  the bottom left coordinate. in Original BBC BASIC it is set with an additional VDU 29 statement. Used the code below to test this behavior:

10 MODE 1
20 VDU 24,150;300;1100;700;
30 GCOL 0,129: CLG
40 MOVE 0,0
50 DRAW 1100,700

To have the same effect on my BBC Micro, I had to add  the following line:
35 VDU 29,150;300;

Tested with the latest releases.

**Comment by breakintoprogram** [comment]
Ok, should be an easy fix.

**Comment by stevesims** [comment]
Verified.

Took a little while to work this one out, as at first glance it looks like all the graphics code is doing the right thing.

Long story short, when you've set a graphics viewport, calls within the VDP code for working out graphics point positions (in the `translateViewport` call) were getting their pixel locations adjusted to be relative to the viewport as well as the origin.  they shouldn't.  that routine should _only_ be doing its calculations relative to origin.

I'll raise a PR in the morning.

**Comment by stevesims** [comment]
PRs raised with a fix

long story short, removing viewport adjustment from `translateViewport` turns that function into a clone of `translateCanvas`, so it's been got rid of

**Comment by leventp** [comment]
Thanks Steve. Also appreciate refactoring of the code.
