### ISSUE TITLE
Send cursor position VDU command doesn't match documentation

### ISSUE THREAD

**Issue by stevesims** [breakintoprogram/agon-vdp#82]
`VDU 23,0,&82` is "request cursor position" - the code is hard-coded right now to return the text cursor position, however it's possible to swap the active cursor to the graphics cursor.

This should probably change to use activeCursor

**Comment by breakintoprogram** [comment]
Hi @stevesims thank you for your comment. Yep, it is designed to return the text cursor position. I will amend the documentation and close this card.

**Comment by breakintoprogram** [comment]
Documentation changed to read 'Request text cursor position' ([link](https://github.com/breakintoprogram/agon-docs/wiki/VDP#vdu-23-0-vpd-commands))
